
name: Build Go Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: List directory structure
      run: |
        ls -R

    - name: Build
      run: |
        # 寻找包含 main 函数的 Go 文件
        main_file=$(find . -name "*.go" -type f -exec grep -l "func main()" {} +)
        if [ -z "$main_file" ]; then
          echo "No Go file with main function found"
          exit 1
        fi
        echo "Building $main_file"
        dir=$(dirname "$main_file")
        cd "$dir"
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o chat .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: chat
        path: ${{ github.workspace }}/chat
