name: Build Go Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: List repository structure
      run: |
        ls -R

    - name: Build
      run: |
        if [ -d "chat" ]; then
          cd chat
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o chat .
        else
          echo "chat directory not found"
          exit 1
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: chat
        path: chat/chat

    - name: Debug Info
      if: failure()
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -R
        echo "Go environment:"
        go env
        echo "Go modules:"
        if [ -d "chat" ]; then
          cd chat
          go list -m all
        else
          echo "chat directory not found"
        fi
